### ISSUE TITLE
Setzten eines µC-Ausgangs implementieren

### ISSUE THREAD

**Issue by marvinmai** [NodeMCU-Home-Automation/Home-Automation-App#2]
Durch einen Button soll ein Ausgang des NodeMCUs gesetzt werden können, schaltend oder tastend.
Hierfür wird von der App eine Netzwerkschnittstelle angesprochen, die wiederrum eine Netzwerkschnittstelle zum NodeMCU anspricht. Verwendet wird die selbe Funktion, mit der ein Ausgangs getogglet wird, Details in Dokumentation.

**Comment by Nunay** [comment]
Funktioniert

IP-Adresse noch von hand einprogrammiert
